### ISSUE TITLE
NVI ack

### ISSUE THREAD

**Issue by tpaxia** [4sun5bu/Z8001MB#1]
Maybe I am missing something but it looks like the 74F138 in iodev.sch is responding to a vectored interrupt ack transaction (ST3..0 = 0,1,1,1) but the Z8530 is raising a NVI.

**Comment by 4sun5bu** [comment]
I haven't confirmed the Z8530 interrupt yet. The VI Acknowledge is connected for VI not for NVI. The Z8530 shoud not need #INTACK for the Non Vector Interrupt. During NVI transaction, #INTACK is kept H. I think it works.

**Comment by tpaxia** [comment]
Thanks. If the idea is to use VI, then why is the INT from the 8530 connected to the Z8001 NVI?

**Comment by 4sun5bu** [comment]
My first design was connecting the INT to the VI, and  switched to the NVI later because the Z8530 setting is a bit confusing for me. But I keep the VI Acknowledge connection to try someday.
