### ISSUE TITLE
Questions about segmentation and separate I/D

### ISSUE THREAD

**Issue by sbelectronics** [4sun5bu/Z8001MB#2]
Hello, I'm trying to understand the handling of separate I and D segments. Your board supports 256K, which means 4 segments of 64K each. Looking at the mapping in the PLD:

   * segments 0-3 map to pages 0-3 in RAM
   * segments 4-7 map to pages 0-3 in RAM (these shadow segments 0-3)
   * segment 8 maps to page 1 in Instruction-mode, or page 2 in Data-mode
   * segment 9 maps to page 0
   * segment 10 maps to page 1

From the above, I can see how we get separate I and D spaces for segment 8, and I can see that segment 8's instructions are available as segment 10's data (as described in biosmem.s). My questions are:

1) Why did you choose segments 8 and 10 for this? Is there something in CP/M-8000 that treats segment 8 specially?

2) Why are segments 4-7 shadowed onto segments 0-3 ?

3) Is there a place in the BIOS that hardcodes the total memory size? My naïve guess would be that you'd just loop until you saw a SEGT asserted, but I can see that your board doesn't implement SEGT, so I'm assuming it must be hardcoded somewhere.

Thanks!

**Comment by 4sun5bu** [comment]
Hello, sbelectronics. Thank you for your interest in my project. This segment mapping is based on Olivetti M20 BIOS, and is a bit confusing.

- Page 1 is shared with I/D merged command and Instruction code of I/D split command.  CP/M-8000 runs a 
loaded command through segment 8 for I/D split command or 10 for I/D merged command.   Segment 11 is used to access the I space of segment 8 as Data.
- Segment 4-7 , there is no meaning in that.  They are reserved for memory expansion, but not used.
- There is no memory size definition in my BIOS. Instead, there is memtbl in bioscall4.s. This table defines segment  mapping and  number of memory regions.               

Thanks.

**Comment by sbelectronics** [comment]
Thanks for the background, 4sun5bu. I've been looking at the memtbl and trying to get some more information on it from the CP/M-8000 manuals that I've found online (which unfortunately hasn't been a whole lot).

I can see how the memtbl maps regions to the various segments. Is there a reason for choosing the region numbers as you have done? For example in the split ID configuration, regions 2 and 3 are the separate I and D regions. Does the CP/M distribution or programs compiled for it mandate those region numbers? If we added additional regions for additional memory, would we expect the CP/M-8000 distribution to be smart enough to take advantage of them?

I am working on my own board, and I plan to keep your numbering scheme for the regions, though I might choose different segment numbers (and the associated decoding) for my implementation.

Thanks

**Comment by 4sun5bu** [comment]
I have no idea about memory regions. We don't have enough information about CP/M-8000, as you know. 

I guess region 1-3 are fixed and are used in the program loader in BDOS.  So, you don't need to mandate region numbers when compiling.  If you want to use specific region in your program, I think it possible.  For instance, DDT uses region 4. It  makes self copy in region 4 and jump there after running. 

When we added memory, CP/M-8000 would not detect and not use them. We need to add regions.

**Comment by sbelectronics** [comment]
Thanks for the info, my board is generally working. I've tested it with both shared segment binaries (eg PIP.Z8J) and split-I/D binaries (eg SIZEZ8K.Z8K).

The one thing that's not working for me is ZCC. Without an argument it will run and print a message as expected. But if I run ZCC with the filename of a valid C program, even something as simple as a "hello world" application, the command will hang until I reset the board.

Did you have any problems running ZCC with your board?

**Comment by 4sun5bu** [comment]
ZCC without argument prints out only version number, and does not do anything.
On my machine ZCC compile a C source code file, and generates an object file.
Then you need to link STARTUP.O and LIBCPM.A with LDZ8K. 

I put a captured terminal image to show how to compile "hello world".

![ZCC](https://user-images.githubusercontent.com/52913666/181501936-9410c8cb-e221-45a3-9982-dbb0a782ad46.png)

**Comment by sbelectronics** [comment]
Thanks, it seems I do have an intermittent problem with my board (I've made some different choices in my hardware than yours), either with memory writes or with program execution. Short commands work fine, but something as large and complex as zcc always fails. I've added a memory test to the monitor, and I can see my tests occasionally failing.
